### ISSUE TITLE
Change Content to IgnoreColors and await for getAllTestResults

### ISSUE THREAD

**Issue by AugustineJosephAlludo** [PeterNgTr/codeceptjs-applitoolshelper#12]
- Content is now updated to IgnoreColors in Applitools.
- getAllTestResults method returns a promise. Hence an await will give consistent result

**Comment by AugustineJosephAlludo** [comment]
@kobenguyent could you give me access so that I can fix this issue

**Comment by kobenguyent** [comment]
@AugustineJosephAlludo please fork the project then you could ofc open a PR from there.

**Comment by AugustineJosephAlludo** [comment]
@kobenguyent Forked and created PR #13 

please review and merge if everything looks fine

**Comment by kobenguyent** [comment]
thank you @AugustineJosephAlludo! We just refactored the code and moved to TS, so those issues are also resolved.
https://github.com/kobenguyent/codeceptjs-applitoolshelper/blob/master/src/types.ts#L21

Closed for now!
