### ISSUE TITLE
Image difference is not failing the test or no option to make test fail if there is image difference

### ISSUE THREAD

**Issue by AugustineJosephAlludo** [PeterNgTr/codeceptjs-applitoolshelper#9]
1. When there is a difference between Checkpoint Image and Baseline image test is not failing or no option to fail it via a parameter to do the same. **_Expected Behaviour:_** Test should fail or there should be option make it fail based on the difference between Checkpoint Image and Baseline image.

2. Also Error is happening which causes confusion while checking logs:
<img width="1045" alt="Screenshot 2024-01-20 at 7 35 05 PM" src="https://github.com/kobenguyent/codeceptjs-applitoolshelper/assets/151602419/4e952b61-ee9b-4138-8405-5e522e69eb69">

3.  Helper should be independent of node version. Like it should be working in any version, not for too old versions at least from node version 14 to latest stable

**Comment by AugustineJosephAlludo** [comment]
@kobenguyent could you please fix these 3 issues

**Comment by kobenguyent** [comment]
Hey @AugustineJosephAlludo thanks for your report! Please provide a sample repo if possible so that we could reproduce your findings, hence it's easier to fix them faster.

**Comment by AugustineJosephAlludo** [comment]
Hi @kobenguyent due to security concerns from our client we are not able to provide sample repo.
I have only used the I.eyeCheck method in the following way: 

- I.eyeCheck({ pageName: page, matchLevel: 'Strict' });
- I.eyeCheck({ pageName: elementName, element: locatorInString, matchLevel: 'Strict'});

**Comment by kobenguyent** [comment]
So, now eyecheck will throw error and failed test accordingly.
Regarding the node version, this lib has no control on which node version shall be supported rather depends on the CodeceptJS the Test Automation framework and Applitools lib.

**Comment by AugustineJosephAlludo** [comment]
@kobenguyent Thanks for the immediate fix. Its working as expected now
